"use client";

import { useState } from "react";
import { FileText, Download, Loader2, Clock, TrendingUp, AlertTriangle, CheckCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Progress } from "@/components/ui/progress";
import { generateReport } from "@/lib/hooks";
import type { UptimeReport, PerformanceReport, IncidentReport, Report } from "@/lib/api";

type ReportType = "uptime" | "performance" | "incident";
type Period = "24h" | "7d" | "30d";

export function ReportsPanel() {
  const [activeTab, setActiveTab] = useState<ReportType>("uptime");
  const [period, setPeriod] = useState<Period>("24h");
  const [isLoading, setIsLoading] = useState(false);
  const [report, setReport] = useState<Report | null>(null);

  const handleGenerateReport = async () => {
    setIsLoading(true);
    try {
      const data = await generateReport(activeTab, period);
      setReport(data);
    } catch (error) {
      console.error("Failed to generate report:", error);
    } finally {
      setIsLoading(false);
    }
  };

  const handleExport = (format: "json" | "markdown") => {
    if (!report) return;

    let content: string;
    let filename: string;
    let mimeType: string;

    if (format === "json") {
      content = JSON.stringify(report, null, 2);
      filename = `${report.type}-report-${period}.json`;
      mimeType = "application/json";
    } else {
      content = generateMarkdown(report);
      filename = `${report.type}-report-${period}.md`;
      mimeType = "text/markdown";
    }

    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const generateMarkdown = (report: Report): string => {
    const date = new Date(report.generated).toLocaleString();
    let md = `# ${report.type.charAt(0).toUpperCase() + report.type.slice(1)} Report\n\n`;
    md += `**Generated:** ${date}\n`;
    md += `**Period:** ${report.period}\n\n`;

    if (report.type === "uptime") {
      const r = report as UptimeReport;
      md += `## Summary\n\n`;
      md += `- **Overall Uptime:** ${r.overall_uptime.toFixed(2)}%\n`;
      md += `- **Total Checks:** ${r.total_checks}\n\n`;
      md += `## Monitors\n\n`;
      md += `| Monitor | Target | Type | Uptime | Checks | Success | Fail |\n`;
      md += `|---------|--------|------|--------|--------|---------|------|\n`;
      r.monitors.forEach(m => {
        md += `| ${m.name} | ${m.target} | ${m.type} | ${m.uptime_percent.toFixed(2)}% | ${m.total_checks} | ${m.success_count} | ${m.fail_count} |\n`;
      });
    } else if (report.type === "performance") {
      const r = report as PerformanceReport;
      md += `## Performance Metrics\n\n`;
      md += `| Monitor | Type | Avg (ms) | Min (ms) | Max (ms) | Checks | Success Rate |\n`;
      md += `|---------|------|----------|----------|----------|--------|-------------|\n`;
      r.monitors.forEach(m => {
        md += `| ${m.name} | ${m.type} | ${m.avg_latency.toFixed(1)} | ${m.min_latency} | ${m.max_latency} | ${m.check_count} | ${m.success_rate.toFixed(1)}% |\n`;
      });
    } else if (report.type === "incident") {
      const r = report as IncidentReport;
      md += `## Summary\n\n`;
      md += `- **Total Incidents:** ${r.total}\n`;
      md += `- **Critical:** ${r.critical}\n`;
      md += `- **Warning:** ${r.warning}\n`;
      md += `- **Resolved:** ${r.resolved}\n\n`;
      if (r.incidents.length > 0) {
        md += `## Incidents\n\n`;
        r.incidents.forEach(i => {
          md += `### ${i.title}\n`;
          md += `- **Severity:** ${i.severity}\n`;
          md += `- **Message:** ${i.message}\n`;
          md += `- **Acknowledged:** ${i.acknowledged ? "Yes" : "No"}\n\n`;
        });
      }
    }

    md += `\n---\n*Report generated by Jorge SRE Platform*\n`;
    return md;
  };

  const renderUptimeReport = (r: UptimeReport) => (
    <div className="space-y-6">
      <div className="grid grid-cols-3 gap-4">
        <Card className="glass-card border-border">
          <CardContent className="pt-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-3xl font-semibold tracking-tight text-emerald-500">
                  {r.overall_uptime.toFixed(2)}%
                </p>
                <p className="text-xs text-muted-foreground mt-1">Overall Uptime</p>
              </div>
              <CheckCircle className="h-6 w-6 text-emerald-500/50" />
            </div>
          </CardContent>
        </Card>
        <Card className="glass-card border-border">
          <CardContent className="pt-4">
            <p className="text-3xl font-semibold tracking-tight">{r.total_checks}</p>
            <p className="text-xs text-muted-foreground mt-1">Total Checks</p>
          </CardContent>
        </Card>
        <Card className="glass-card border-border">
          <CardContent className="pt-4">
            <p className="text-3xl font-semibold tracking-tight">{r.monitors.length}</p>
            <p className="text-xs text-muted-foreground mt-1">Monitors</p>
          </CardContent>
        </Card>
      </div>

      <Card className="glass-card border-border">
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-medium">Monitor Uptime</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {r.monitors.map((m) => (
              <div key={m.id} className="space-y-2">
                <div className="flex items-center justify-between text-sm">
                  <div className="flex items-center gap-2">
                    <span className="font-medium">{m.name}</span>
                    <span className="text-xs text-muted-foreground uppercase">{m.type}</span>
                  </div>
                  <span className={`font-mono ${m.uptime_percent >= 99.9 ? "text-emerald-500" : m.uptime_percent >= 99 ? "text-amber-500" : "text-red-500"}`}>
                    {m.uptime_percent.toFixed(2)}%
                  </span>
                </div>
                <Progress value={m.uptime_percent} className="h-1.5" />
                <div className="flex justify-between text-xs text-muted-foreground">
                  <span>{m.success_count} successful</span>
                  <span>{m.fail_count} failed</span>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );

  const renderPerformanceReport = (r: PerformanceReport) => (
    <div className="space-y-6">
      <Card className="glass-card border-border">
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-medium">Performance Metrics</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border">
                  <th className="text-left py-2 font-medium">Monitor</th>
                  <th className="text-left py-2 font-medium">Type</th>
                  <th className="text-right py-2 font-medium">Avg (ms)</th>
                  <th className="text-right py-2 font-medium">Min (ms)</th>
                  <th className="text-right py-2 font-medium">Max (ms)</th>
                  <th className="text-right py-2 font-medium">Checks</th>
                  <th className="text-right py-2 font-medium">Success Rate</th>
                </tr>
              </thead>
              <tbody>
                {r.monitors.map((m) => (
                  <tr key={m.id} className="border-b border-border/50">
                    <td className="py-2">{m.name}</td>
                    <td className="py-2 text-muted-foreground uppercase text-xs">{m.type}</td>
                    <td className="py-2 text-right font-mono">{m.avg_latency.toFixed(1)}</td>
                    <td className="py-2 text-right font-mono text-muted-foreground">{m.min_latency}</td>
                    <td className="py-2 text-right font-mono text-muted-foreground">{m.max_latency}</td>
                    <td className="py-2 text-right">{m.check_count}</td>
                    <td className={`py-2 text-right font-medium ${m.success_rate >= 99 ? "text-emerald-500" : m.success_rate >= 95 ? "text-amber-500" : "text-red-500"}`}>
                      {m.success_rate.toFixed(1)}%
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>
    </div>
  );

  const renderIncidentReport = (r: IncidentReport) => (
    <div className="space-y-6">
      <div className="grid grid-cols-4 gap-4">
        <Card className="glass-card border-border">
          <CardContent className="pt-4">
            <p className="text-3xl font-semibold tracking-tight">{r.total}</p>
            <p className="text-xs text-muted-foreground mt-1">Total Incidents</p>
          </CardContent>
        </Card>
        <Card className="glass-card border-border">
          <CardContent className="pt-4">
            <p className="text-3xl font-semibold tracking-tight text-red-500">{r.critical}</p>
            <p className="text-xs text-muted-foreground mt-1">Critical</p>
          </CardContent>
        </Card>
        <Card className="glass-card border-border">
          <CardContent className="pt-4">
            <p className="text-3xl font-semibold tracking-tight text-amber-500">{r.warning}</p>
            <p className="text-xs text-muted-foreground mt-1">Warning</p>
          </CardContent>
        </Card>
        <Card className="glass-card border-border">
          <CardContent className="pt-4">
            <p className="text-3xl font-semibold tracking-tight text-emerald-500">{r.resolved}</p>
            <p className="text-xs text-muted-foreground mt-1">Resolved</p>
          </CardContent>
        </Card>
      </div>

      {r.incidents.length > 0 && (
        <Card className="glass-card border-border">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium">Incident Timeline</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {r.incidents.map((incident) => (
                <div key={incident.ID} className="flex items-start gap-3 py-2 border-b border-border last:border-0">
                  <div className={`h-2 w-2 rounded-full mt-1.5 ${
                    incident.severity === "critical" ? "bg-red-500" : "bg-amber-500"
                  }`} />
                  <div className="flex-1">
                    <p className="text-sm font-medium">{incident.title}</p>
                    <p className="text-xs text-muted-foreground mt-0.5">{incident.message}</p>
                    <div className="flex gap-3 mt-1 text-xs text-muted-foreground">
                      <span className={`uppercase ${incident.severity === "critical" ? "text-red-500" : "text-amber-500"}`}>
                        {incident.severity}
                      </span>
                      <span>{incident.acknowledged ? "Acknowledged" : "Pending"}</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {r.incidents.length === 0 && (
        <Card className="glass-card border-border">
          <CardContent className="py-12 text-center">
            <CheckCircle className="h-12 w-12 text-emerald-500/30 mx-auto mb-3" />
            <p className="text-muted-foreground">No incidents during this period</p>
          </CardContent>
        </Card>
      )}
    </div>
  );

  return (
    <div className="space-y-8">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-medium tracking-tight">Reports</h1>
          <p className="text-sm text-muted-foreground mt-1">
            Generate and export monitoring reports
          </p>
        </div>
      </div>

      <Tabs value={activeTab} onValueChange={(v) => { setActiveTab(v as ReportType); setReport(null); }}>
        <div className="flex items-center justify-between mb-6">
          <TabsList className="grid grid-cols-3 w-auto">
            <TabsTrigger value="uptime" className="gap-2">
              <Clock className="h-4 w-4" />
              Uptime
            </TabsTrigger>
            <TabsTrigger value="performance" className="gap-2">
              <TrendingUp className="h-4 w-4" />
              Performance
            </TabsTrigger>
            <TabsTrigger value="incident" className="gap-2">
              <AlertTriangle className="h-4 w-4" />
              Incidents
            </TabsTrigger>
          </TabsList>

          <div className="flex items-center gap-2">
            <div className="flex gap-1">
              {(["24h", "7d", "30d"] as Period[]).map((p) => (
                <Button
                  key={p}
                  variant={period === p ? "secondary" : "ghost"}
                  size="sm"
                  className="h-8"
                  onClick={() => { setPeriod(p); setReport(null); }}
                >
                  {p}
                </Button>
              ))}
            </div>
            <Button size="sm" className="h-8" onClick={handleGenerateReport} disabled={isLoading}>
              {isLoading ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <>
                  <FileText className="h-4 w-4 mr-1" />
                  Generate
                </>
              )}
            </Button>
          </div>
        </div>

        {report && (
          <div className="flex justify-end gap-2 mb-4">
            <Button variant="outline" size="sm" onClick={() => handleExport("markdown")}>
              <Download className="h-4 w-4 mr-1" />
              Export Markdown
            </Button>
            <Button variant="outline" size="sm" onClick={() => handleExport("json")}>
              <Download className="h-4 w-4 mr-1" />
              Export JSON
            </Button>
          </div>
        )}

        <TabsContent value="uptime">
          {report && report.type === "uptime" ? (
            renderUptimeReport(report as UptimeReport)
          ) : (
            <Card className="glass-card border-border">
              <CardContent className="py-16 text-center">
                <Clock className="h-12 w-12 text-muted-foreground/30 mx-auto mb-3" />
                <p className="text-muted-foreground">Click "Generate" to create an uptime report</p>
                <p className="text-sm text-muted-foreground/70 mt-1">Shows monitor availability and health status</p>
              </CardContent>
            </Card>
          )}
        </TabsContent>

        <TabsContent value="performance">
          {report && report.type === "performance" ? (
            renderPerformanceReport(report as PerformanceReport)
          ) : (
            <Card className="glass-card border-border">
              <CardContent className="py-16 text-center">
                <TrendingUp className="h-12 w-12 text-muted-foreground/30 mx-auto mb-3" />
                <p className="text-muted-foreground">Click "Generate" to create a performance report</p>
                <p className="text-sm text-muted-foreground/70 mt-1">Shows latency metrics and response times</p>
              </CardContent>
            </Card>
          )}
        </TabsContent>

        <TabsContent value="incident">
          {report && report.type === "incident" ? (
            renderIncidentReport(report as IncidentReport)
          ) : (
            <Card className="glass-card border-border">
              <CardContent className="py-16 text-center">
                <AlertTriangle className="h-12 w-12 text-muted-foreground/30 mx-auto mb-3" />
                <p className="text-muted-foreground">Click "Generate" to create an incident report</p>
                <p className="text-sm text-muted-foreground/70 mt-1">Shows alerts and outage history</p>
              </CardContent>
            </Card>
          )}
        </TabsContent>
      </Tabs>
    </div>
  );
}
