### GET resources catalog
GET http://localhost:8080/api/v1/resources/name?name=consul

### GET resources catalog
GET http://localhost:8080/api/v1/resources

### POST resources catalog
POST http://localhost:8080/api/v1/resource
content-type: application/json

{
    "name":"consul",
    "dns":"test.consul.com.br"
}
### DELETE resources catalog
DELETE http://localhost:8080/api/v1/resource?id=7

### PUT resources catalog
PUT http://localhost:8080/api/v1/resource?id=7

{
    "name":"consul",
    "dns":"test.consul.com.br"
}